// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"easygoadmin/app/model/internal"
	"github.com/gogf/gf/os/gtime"
)

// Ad is the golang structure for table sys_ad.
type Ad internal.Ad

// Fill with you ideas below.

// 列表查询
type AdPageReq struct {
	Title string `p:"title"` // 广告标题
	Page  int    `p:"page"`  // 页码
	Limit int    `p:"limit"` // 每页数
}

// 添加广告
type AdAddReq struct {
	Title       string      `p:"title"       v:"required#广告标题不能为空"`    // 广告标题
	AdSortId    int         `p:"ad_sort_id"  v:"required#广告位描述ID不能为空"` // 广告位ID
	Cover       string      `p:"cover"`                                // 广告图片
	Type        int         `p:"type"        v:"required#请选择广告类型"`     // 广告格式：1图片 2文字 3视频 4推荐
	Description string      `p:"description" v:"required#广告描述不能为空"`    // 广告描述
	Content     string      `p:"content"`                              // 广告内容
	Url         string      `p:"url"         v:"required#广告连接不能为空"`    // 广告链接
	Width       int         `p:"width"`                                // 广告宽度
	Height      int         `p:"height"`                               // 广告高度
	StartTime   *gtime.Time `p:"start_time"  v:"required#广告开始时间不能为空"`  // 开始时间
	EndTime     *gtime.Time `p:"end_time"    v:"required#广告结束时间不能为空"`  // 结束时间
	Status      int         `p:"status"      v:"required#请选择广告状态"`     // 状态：1在用 2停用
	Sort        int         `p:"sort"        v:"required#排序号不能为空"`     // 排序
}

// 更新广告
type AdUpdateReq struct {
	Id          int         `p:"id" v:"required#主键ID不能为空"`
	Title       string      `p:"title"       v:"required#广告标题不能为空"`    // 广告标题
	AdSortId    int         `p:"ad_sort_id"  v:"required#广告位描述ID不能为空"` // 广告位ID
	Cover       string      `p:"cover"`                                // 广告图片
	Type        int         `p:"type"        v:"required#请选择广告类型"`     // 广告格式：1图片 2文字 3视频 4推荐
	Description string      `p:"description" v:"required#广告描述不能为空"`    // 广告描述
	Content     string      `p:"content"`                              // 广告内容
	Url         string      `p:"url"         v:"required#广告连接不能为空"`    // 广告链接
	Width       int         `p:"width"`                                // 广告宽度
	Height      int         `p:"height"`                               // 广告高度
	StartTime   *gtime.Time `p:"start_time"  v:"required#广告开始时间不能为空"`  // 开始时间
	EndTime     *gtime.Time `p:"end_time"    v:"required#广告结束时间不能为空"`  // 结束时间
	Status      int         `p:"status"      v:"required#请选择广告状态"`     // 状态：1在用 2停用
	Sort        int         `p:"sort"        v:"required#排序号不能为空"`     // 排序
}

// 删除广告
type AdDeleteReq struct {
	Ids string `p:"ids" v:"required#请选择需要删除的数据记录"`
}

// 设置状态
type AdStatusReq struct {
	Id     int `p:"id" v:"required#主键ID不能为空"`
	Status int `p:"status"    v:"required#广告状态不能为空"`
}

// 广告信息Vo
type AdInfoVo struct {
	Ad
	TypeName   string `json:"typeName"`   // 广告类型
	AdSortDesc string `json:"adSortDesc"` // 广告位描述
}
