// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"easygoadmin/app/model/internal"
)

// AdSort is the golang structure for table sys_ad_sort.
type AdSort internal.AdSort

// Fill with you ideas below.

// 列表查询条件
type AdSortPageReq struct {
	Description string `p:"name"`  // 广告位描述
	Page        int    `p:"page"`  // 页码
	Limit       int    `p:"limit"` // 每页数
}

// 添加广告位
type AdSortAddReq struct {
	Description string `p:"description" v:"required#广告位描述不能为空"` // 广告位描述
	ItemId      int    `p:"item_id"     v:"required#请选择站点"`     // 站点ID
	CateId      int    `p:"cate_id"     v:"required#请选择栏目"`     // 栏目ID
	LocId       int    `p:"loc_id"      v:"required#广告位置不能为空"`  // 广告页面位置
	Platform    int    `p:"platform"    v:"required#投放平台不能为空"`  // 站点类型：1PC网站 2WAP手机站 3微信小程序 4APP移动端
	Sort        int    `p:"sort"        v:"required#排序号不能为空"`   // 广告位排序
}

// 更新广告位
type AdSortUpdateReq struct {
	Id          int    `p:"id" v:"required#主键ID不能为空"`
	Description string `p:"description" v:"required#广告位描述不能为空"` // 广告位描述
	ItemId      int    `p:"item_id"     v:"required#请选择站点"`     // 站点ID
	CateId      int    `p:"cate_id"     v:"required#请选择栏目"`     // 栏目ID
	LocId       int    `p:"loc_id"      v:"required#广告位置不能为空"`  // 广告页面位置
	Platform    int    `p:"platform"    v:"required#投放平台不能为空"`  // 站点类型：1PC网站 2WAP手机站 3微信小程序 4APP移动端
	Sort        int    `p:"sort"        v:"required#排序号不能为空"`   // 广告位排序
}

type AdSortDeleteReq struct {
	Ids string `p:"ids" v:"required#请选择需要删除的数据记录"`
}

// 广告位信息
type AdSortInfoVo struct {
	AdSort
	ItemName     string `json:"itemName"`     // 站点名称
	CateName     string `json:"cateName"`     // 栏目名称
	PlatformName string `json:"platformName"` // 所属平台
}
