// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"easygoadmin/app/model/internal"
)

// City is the golang structure for table sys_city.
type City internal.City

// Fill with you ideas below.

type CityInfoVo struct {
	City
	HaveChild bool `json:"haveChild"`
}

// 列表查询条件
type CityQueryReq struct {
	Name string `p:"name"` // 城市名称
	Pid  int    `p:pid`    // 上级ID
}

// 添加城市
type CityAddReq struct {
	Pid      int    `p:"pid"`                               // 父级编号
	Level    int    `p:"level"       v:"required#请选择城市等级"`  // 城市级别：1省 2市 3区
	Name     string `p:"name"        v:"required#城市名称不能为空"` // 城市名称
	Citycode string `p:"citycode"`                          // 城市编号（区号）
	PAdcode  string `p:"p_adcode"`                          // 父级地理编号
	Adcode   string `p:"adcode"`                            // 地理编号
	Lng      uint   `p:"lng"`                               // 城市坐标中心点经度（* 1e6）：如果是中国，此值是 1e7
	Lat      uint   `p:"lat"`                               // 城市坐标中心点纬度（* 1e6）
	Sort     int    `p:"sort"        v:"required#排序号不能为空"`  // 排序号
}

// 编辑城市
type CityUpdateReq struct {
	Id       int    `p:id v:"required#主键ID不能为空"`            // 主键ID
	Pid      int    `p:"pid"`                               // 父级编号
	Level    int    `p:"level"       v:"required#请选择城市等级"`  // 城市级别：1省 2市 3区
	Name     string `p:"name"        v:"required#城市名称不能为空"` // 城市名称
	Citycode string `p:"citycode"`                          // 城市编号（区号）
	PAdcode  string `p:"p_adcode"`                          // 父级地理编号
	Adcode   string `p:"adcode"`                            // 地理编号
	Lng      uint   `p:"lng"`                               // 城市坐标中心点经度（* 1e6）：如果是中国，此值是 1e7
	Lat      uint   `p:"lat"`                               // 城市坐标中心点纬度（* 1e6）
	Sort     int    `p:"sort"        v:"required#排序号不能为空"`  // 排序号
}

// 删除城市
type CityDeleteReq struct {
	Ids string `p:ids v:"required#请选择需要删除的数据记录"`
}

// 获取子级城市
type CityChildReq struct {
	CityCode string `p:id v:"required#上级城市编码不能为空"`
}
