// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"easygoadmin/app/model/internal"
)

// Dept is the golang structure for table sys_dept.
type Dept internal.Dept

// Fill with you ideas below.

type DeptPageReq struct {
	Name string `p:"name"` // 部门名称
}

// 添加部门
type DeptAddReq struct {
	Name     string `p:"name" v:"required#部门名称不能为空"`
	Code     string `p:"code" v:"required#部门编码不能为空"`
	Fullname string `p:"fullname" v:"required#部门全称不能为空"`
	Type     int    `p:type v:"required#请选择部门类型"`
	Pid      int    `p:"pid"` // 上级ID
	Sort     int    `p:sort v:"required#部门排序不能为空"`
	Note     string
}

// 部门编辑
type DeptUpdateReq struct {
	Id       int    `p:id v:"required#主键ID不能为空"`
	Name     string `p:"name" v:"required#部门名称不能为空"`
	Code     string `p:"code" v:"required#部门编码不能为空"`
	Fullname string `p:"fullname" v:"required#部门全称不能为空"`
	Type     int    `p:type v:"required#请选择部门类型"`
	Pid      int    `p:"pid"` // 上级ID
	Sort     int    `p:sort v:"required#部门排序不能为空"`
	Note     string
}

// 部门删除
type DeptDeleteReq struct {
	Ids string `p:ids v:"required#请选择需要删除的数据记录"`
}

// 部门树结构
type DeptTreeNode struct {
	Dept
	Children []*DeptTreeNode `json:"children"` // 子栏目
}
