// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"easygoadmin/app/model/internal"
)

// Dict is the golang structure for table sys_dict.
type Dict internal.Dict

// Fill with you ideas below.

// 字典查询条件
type DictQueryReq struct {
	Name string `p:"name"` // 字典名称
}

// 添加字典
type DictAddReq struct {
	Name string `p:"name"  v:"required#字典名称不能为空"` // 字典名称
	Code string `p:"code"  v:"required#字典编码不能为空"` // 字典值
	Sort int    `p:"sort"  v:"required#字典排序不能为空"` // 显示顺序
	Note string `p:"note"`                        // 字典备注
}

// 修改字典
type DictUpdateReq struct {
	Id   int    `p:"id" v:"required#主键ID不能为空"`    // 主键ID
	Name string `p:"name"  v:"required#字典名称不能为空"` // 字典名称
	Code string `p:"code"  v:"required#字典编码不能为空"` // 字典值
	Sort int    `p:"sort"  v:"required#字典排序不能为空"` // 显示顺序
	Note string `p:"note"`                        // 字典备注
}

// 删除字典
type DictDeleteReq struct {
	Ids string `p:"ids" v:"required#请选择需要删除的数据记录"`
}
