// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"easygoadmin/app/model/internal"
)

// Level is the golang structure for table sys_level.
type Level internal.Level

// Fill with you ideas below.

// 分页查询条件
type LevelQueryReq struct {
	Name  string `p:"name"` // 职级名称
	Page  int    `p:page`   // 页码
	Limit int    `p:limit`  // 每页数
}

// 添加职级
type LevelAddReq struct {
	Name   string `p:"name"  v:"required#职级名称不能为空"`
	Status int    `p:"status"    v:"required#职级状态不能为空"`
	Sort   int    `p:"sort"  v:"required#显示顺序不能为空"`
}

// 编辑职级
type LevelEditReq struct {
	Id     int  `p:"id" v:"required#主键ID不能为空"`
	Name   string `p:"name"  v:"required#职级名称不能为空"`
	Status int    `p:"status"    v:"required#职级状态不能为空"`
	Sort   int    `p:"sort"  v:"required#显示顺序不能为空"`
}

// 删除职级
type LevelDeleteReq struct {
	Ids string `p:"ids"  v:"required#请选择要删除的数据记录"`
}

// 设置状态
type LevelStatusReq struct {
	Id     int `p:"id" v:"required#主键ID不能为空"`
	Status int `p:"status"    v:"required#职级状态不能为空"`
}
