// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"easygoadmin/app/model/internal"
)

// MemberLevel is the golang structure for table ums_member_level.
type MemberLevel internal.MemberLevel

// Fill with you ideas below.

// 查询会员等级
type MemberLevelPageReq struct {
	Name  string `p:"name"` // 等级名称
	Page  int    `p:page`   // 页码
	Limit int    `p:limit`  // 每页数
}

// 添加会员等级
type MemberLevelAddReq struct {
	Name string `p:"name"        v:"name"` // 级别名称
	Sort int    `p:"sort"        v:"sort"` // 排序号    
}

// 更新会员等级
type MemberLevelUpdateReq struct {
	Id   int    `p:"id" v:"required#主键ID不能为空"`
	Name string `p:"name"        v:"required#会员等级名称不能为空"` // 级别名称
	Sort int    `p:"sort"        v:"required#会员排序号不能为空"`  // 排序号
}

// 删除会员等级
type MemberLevelDeleteReq struct {
	Ids string `p:"ids"  v:"required#请选择要删除的数据记录"`
}
