// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// AdSort is the golang structure for table sys_ad_sort.
type AdSort struct {
    Id          int         `orm:"id,primary"  json:"id"`          // 主键ID                                               
    Description string      `orm:"description" json:"description"` // 广告位描述                                           
    ItemId      int         `orm:"item_id"     json:"itemId"`      // 站点ID                                               
    CateId      int         `orm:"cate_id"     json:"cateId"`      // 栏目ID                                               
    LocId       int         `orm:"loc_id"      json:"locId"`       // 广告页面位置                                         
    Platform    int         `orm:"platform"    json:"platform"`    // 站点类型：1PC网站 2WAP手机站 3微信小程序 4APP移动端  
    Sort        int         `orm:"sort"        json:"sort"`        // 广告位排序                                           
    CreateUser  int         `orm:"create_user" json:"createUser"`  // 添加人                                               
    CreateTime  *gtime.Time `orm:"create_time" json:"createTime"`  // 添加时间                                             
    UpdateUser  int         `orm:"update_user" json:"updateUser"`  // 更新人                                               
    UpdateTime  *gtime.Time `orm:"update_time" json:"updateTime"`  // 更新时间                                             
    Mark        int         `orm:"mark"        json:"mark"`        // 有效标识(1正常 0删除)                                
}