// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// ConfigData is the golang structure for table sys_config_data.
type ConfigData struct {
    Id         int         `orm:"id,primary"  json:"id"`         // 主键ID                 
    Title      string      `orm:"title"       json:"title"`      // 配置标题               
    Code       string      `orm:"code"        json:"code"`       // 配置编码               
    Value      string      `orm:"value"       json:"value"`      // 配置值                 
    Options    string      `orm:"options"     json:"options"`    // 配置项                 
    ConfigId   int         `orm:"config_id"   json:"configId"`   // 配置ID                 
    Type       string      `orm:"type"        json:"type"`       // 配置类型               
    Status     int         `orm:"status"      json:"status"`     // 状态：1正常 2停用      
    Sort       int         `orm:"sort"        json:"sort"`       // 排序                   
    Note       string      `orm:"note"        json:"note"`       // 配置说明               
    CreateUser int         `orm:"create_user" json:"createUser"` // 添加人                 
    CreateTime *gtime.Time `orm:"create_time" json:"createTime"` // 添加时间               
    UpdateUser int         `orm:"update_user" json:"updateUser"` // 更新人                 
    UpdateTime *gtime.Time `orm:"update_time" json:"updateTime"` // 更新时间               
    Mark       int         `orm:"mark"        json:"mark"`       // 有效标识：1正常 0删除  
}