// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Dept is the golang structure for table sys_dept.
type Dept struct {
    Id         int         `orm:"id,primary"  json:"id"`         // 主键ID                           
    Name       string      `orm:"name"        json:"name"`       // 部门名称                         
    Code       string      `orm:"code"        json:"code"`       // 部门编码                         
    Fullname   string      `orm:"fullname"    json:"fullname"`   // 部门全称                         
    Type       int         `orm:"type"        json:"type"`       // 类型：1公司 2子公司 3部门 4小组  
    Pid        int         `orm:"pid"         json:"pid"`        // 上级ID                           
    Sort       int         `orm:"sort"        json:"sort"`       // 排序                             
    Note       string      `orm:"note"        json:"note"`       // 备注说明                         
    CreateUser int         `orm:"create_user" json:"createUser"` // 添加人                           
    CreateTime *gtime.Time `orm:"create_time" json:"createTime"` // 创建时间                         
    UpdateUser int         `orm:"update_user" json:"updateUser"` // 更新人                           
    UpdateTime *gtime.Time `orm:"update_time" json:"updateTime"` // 更新时间                         
    Mark       int         `orm:"mark"        json:"mark"`       // 有效标识                         
}