// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Example is the golang structure for table sys_example.
type Example struct {
    Id         int         `orm:"id,primary"  json:"id"`         // 唯一性标识                                   
    Name       string      `orm:"name"        json:"name"`       // 测试名称                                     
    Avatar     string      `orm:"avatar"      json:"avatar"`     // 头像                                         
    Status     int         `orm:"status"      json:"status"`     // 状态：1正常 2停用                            
    Type       int         `orm:"type"        json:"type"`       // 类型：1京东 2淘宝 3拼多多 4唯品会 5小米有品  
    Content    string      `orm:"content"     json:"content"`    // 内容简介                                     
    IsVip      int         `orm:"is_vip"      json:"isVip"`      // 是否VIP：1是 2否                             
    Sort       int         `orm:"sort"        json:"sort"`       // 显示顺序                                     
    CreateUser int         `orm:"create_user" json:"createUser"` // 添加人                                       
    CreateTime *gtime.Time `orm:"create_time" json:"createTime"` // 添加时间                                     
    UpdateUser int         `orm:"update_user" json:"updateUser"` // 更新人                                       
    UpdateTime *gtime.Time `orm:"update_time" json:"updateTime"` // 更新时间                                     
    Mark       int         `orm:"mark"        json:"mark"`       // 有效标识                                     
}