// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Member is the golang structure for table ums_member.
type Member struct {
    Id           int         `orm:"id,primary"      json:"id"`           //                                               
    Openid       string      `orm:"openid"          json:"openid"`       // 用户唯一标识                                  
    Username     string      `orm:"username,unique" json:"username"`     // 用户名                                        
    Password     string      `orm:"password"        json:"password"`     // 密码                                          
    MemberLevel  int         `orm:"member_level"    json:"memberLevel"`  // 会员等级                                      
    Realname     string      `orm:"realname"        json:"realname"`     // 真实姓名                                      
    Nickname     string      `orm:"nickname"        json:"nickname"`     // 用户昵称                                      
    Gender       int         `orm:"gender"          json:"gender"`       // 性别（1男 2女 3未知）                         
    Avatar       string      `orm:"avatar"          json:"avatar"`       // 用户头像                                      
    Birthday     *gtime.Time `orm:"birthday"        json:"birthday"`     // 出生日期                                      
    ProvinceCode string      `orm:"province_code"   json:"provinceCode"` // 户籍省份编号                                  
    CityCode     string      `orm:"city_code"       json:"cityCode"`     // 户籍城市编号                                  
    DistrictCode string      `orm:"district_code"   json:"districtCode"` // 户籍区/县编号                                 
    Address      string      `orm:"address"         json:"address"`      // 详细地址                                      
    Intro        string      `orm:"intro"           json:"intro"`        // 个人简介                                      
    Signature    string      `orm:"signature"       json:"signature"`    // 个性签名                                      
    Device       int         `orm:"device"          json:"device"`       // 设备类型：1苹果 2安卓 3WAP站 4PC站 5后台添加  
    DeviceCode   string      `orm:"device_code"     json:"deviceCode"`   // 推送的别名                                    
    PushAlias    string      `orm:"push_alias"      json:"pushAlias"`    // 推送的别名                                    
    Source       int         `orm:"source"          json:"source"`       // 来源：1、APP注册；2、后台添加；               
    Status       int         `orm:"status"          json:"status"`       // 是否启用 1、启用  2、停用                     
    AppVersion   string      `orm:"app_version"     json:"appVersion"`   // 客户端版本号                                  
    Code         string      `orm:"code"            json:"code"`         // 我的推广码                                    
    LoginIp      string      `orm:"login_ip"        json:"loginIp"`      // 最近登录IP                                    
    LoginTime    *gtime.Time `orm:"login_time"      json:"loginTime"`    // 登录时间                                      
    LoginRegion  string      `orm:"login_region"    json:"loginRegion"`  // 上次登录地点                                  
    LoginCount   uint        `orm:"login_count"     json:"loginCount"`   // 登录总次数                                    
    CreateUser   int         `orm:"create_user"     json:"createUser"`   // 添加人                                        
    CreateTime   *gtime.Time `orm:"create_time"     json:"createTime"`   // 创建时间                                      
    UpdateUser   int         `orm:"update_user"     json:"updateUser"`   // 修改人                                        
    UpdateTime   *gtime.Time `orm:"update_time"     json:"updateTime"`   // 更新时间                                      
    Mark         int         `orm:"mark"            json:"mark"`         // 有效标识：1正常 0删除                         
}