// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Menu is the golang structure for table sys_menu.
type Menu struct {
    Id         int         `orm:"id,primary"  json:"id"`         // 唯一性标识                     
    ParentId   int         `orm:"parent_id"   json:"parentId"`   // 上级ID                         
    Title      string      `orm:"title"       json:"title"`      // 菜单标题                       
    Icon       string      `orm:"icon"        json:"icon"`       // 菜单图标                       
    Path       string      `orm:"path"        json:"path"`       // 菜单地址                       
    Component  string      `orm:"component"   json:"component"`  // 菜单组件                       
    Target     int         `orm:"target"      json:"target"`     // 打开方式：1内部打开 2外部打开  
    Permission string      `orm:"permission"  json:"permission"` // 权限标识                       
    Type       int         `orm:"type"        json:"type"`       // 类型：1模块 2导航 3菜单 4节点  
    Status     int         `orm:"status"      json:"status"`     // 是否显示：1显示 2不显示        
    Note       string      `orm:"note"        json:"note"`       // 菜单备注                       
    Sort       int         `orm:"sort"        json:"sort"`       // 显示顺序                       
    CreateUser int         `orm:"create_user" json:"createUser"` // 添加人                         
    CreateTime *gtime.Time `orm:"create_time" json:"createTime"` // 添加时间                       
    UpdateUser int         `orm:"update_user" json:"updateUser"` // 更新人                         
    UpdateTime *gtime.Time `orm:"update_time" json:"updateTime"` // 更新时间                       
    Mark       int         `orm:"mark"        json:"mark"`       // 有效标识                       
}