// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Notice is the golang structure for table sys_notice.
type Notice struct {
    Id         int         `orm:"id,primary"  json:"id"`         // 通知ID                     
    Title      string      `orm:"title"       json:"title"`      // 通知标题                   
    Content    string      `orm:"content"     json:"content"`    // 通知内容                   
    Source     int         `orm:"source"      json:"source"`     // 来源：1内部通知 2外部通知  
    IsTop      int         `orm:"is_top"      json:"isTop"`      // 是否置顶：1是 2否          
    Browse     int         `orm:"browse"      json:"browse"`     // 阅读量                     
    Status     int         `orm:"status"      json:"status"`     // 状态：1已发布 2待发布      
    CreateUser int         `orm:"create_user" json:"createUser"` // 添加人                     
    CreateTime *gtime.Time `orm:"create_time" json:"createTime"` // 添加时间                   
    UpdateUser int         `orm:"update_user" json:"updateUser"` // 更新人                     
    UpdateTime *gtime.Time `orm:"update_time" json:"updateTime"` // 更新时间                   
    Mark       int         `orm:"mark"        json:"mark"`       // 有效标识                   
}