// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// AdDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type AdDao struct {
	internal.AdDao
}

var (
	// Ad is globally public accessible object for table sys_ad operations.
	Ad = AdDao{
		internal.Ad,
	}
)

// Fill with you ideas below.