// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// AdSortDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type AdSortDao struct {
	internal.AdSortDao
}

var (
	// AdSort is globally public accessible object for table sys_ad_sort operations.
	AdSort = AdSortDao{
		internal.AdSort,
	}
)

// Fill with you ideas below.