// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// CityDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type CityDao struct {
	internal.CityDao
}

var (
	// City is globally public accessible object for table sys_city operations.
	City = CityDao{
		internal.City,
	}
)

// Fill with you ideas below.