// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// ConfigDataDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type ConfigDataDao struct {
	internal.ConfigDataDao
}

var (
	// ConfigData is globally public accessible object for table sys_config_data operations.
	ConfigData = ConfigDataDao{
		internal.ConfigData,
	}
)

// Fill with you ideas below.