// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// DeptDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type DeptDao struct {
	internal.DeptDao
}

var (
	// Dept is globally public accessible object for table sys_dept operations.
	Dept = DeptDao{
		internal.Dept,
	}
)

// Fill with you ideas below.