// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// DictDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type DictDao struct {
	internal.DictDao
}

var (
	// Dict is globally public accessible object for table sys_dict operations.
	Dict = DictDao{
		internal.Dict,
	}
)

// Fill with you ideas below.