// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// DictDataDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type DictDataDao struct {
	internal.DictDataDao
}

var (
	// DictData is globally public accessible object for table sys_dict_data operations.
	DictData = DictDataDao{
		internal.DictData,
	}
)

// Fill with you ideas below.