// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// example2Dao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type example2Dao struct {
	internal.Example2Dao
}

var (
	// Example2 is globally public accessible object for table sys_example2 operations.
	Example2 = example2Dao{
		internal.Example2,
	}
)

// Fill with you ideas below.