// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// ItemCateDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type ItemCateDao struct {
	internal.ItemCateDao
}

var (
	// ItemCate is globally public accessible object for table sys_item_cate operations.
	ItemCate = ItemCateDao{
		internal.ItemCate,
	}
)

// Fill with you ideas below.