// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// ItemDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type ItemDao struct {
	internal.ItemDao
}

var (
	// Item is globally public accessible object for table sys_item operations.
	Item = ItemDao{
		internal.Item,
	}
)

// Fill with you ideas below.