// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// LevelDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type LevelDao struct {
	internal.LevelDao
}

var (
	// Level is globally public accessible object for table sys_level operations.
	Level = LevelDao{
		internal.Level,
	}
)

// Fill with you ideas below.