// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// LinkDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type LinkDao struct {
	internal.LinkDao
}

var (
	// Link is globally public accessible object for table sys_link operations.
	Link = LinkDao{
		internal.Link,
	}
)

// Fill with you ideas below.