// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// MemberDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type MemberDao struct {
	internal.MemberDao
}

var (
	// Member is globally public accessible object for table ums_member operations.
	Member = MemberDao{
		internal.Member,
	}
)

// Fill with you ideas below.