// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// MenuDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type MenuDao struct {
	internal.MenuDao
}

var (
	// Menu is globally public accessible object for table sys_menu operations.
	Menu = MenuDao{
		internal.Menu,
	}
)

// Fill with you ideas below.