// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// NoticeDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type NoticeDao struct {
	internal.NoticeDao
}

var (
	// Notice is globally public accessible object for table sys_notice operations.
	Notice = NoticeDao{
		internal.Notice,
	}
)

// Fill with you ideas below.