// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// OperLogDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type OperLogDao struct {
	internal.OperLogDao
}

var (
	// OperLog is globally public accessible object for table sys_oper_log operations.
	OperLog = OperLogDao{
		internal.OperLog,
	}
)

// Fill with you ideas below.