// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// RoleMenuDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type RoleMenuDao struct {
	internal.RoleMenuDao
}

var (
	// RoleMenu is globally public accessible object for table sys_role_menu operations.
	RoleMenu = RoleMenuDao{
		internal.RoleMenu,
	}
)

// Fill with you ideas below.