// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// RoleDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type RoleDao struct {
	internal.RoleDao
}

var (
	// Role is globally public accessible object for table sys_role operations.
	Role = RoleDao{
		internal.Role,
	}
)

// Fill with you ideas below.