// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"easygoadmin/app/dao/internal"
)

// UserRoleDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type UserRoleDao struct {
	internal.UserRoleDao
}

var (
	// UserRole is globally public accessible object for table sys_user_role operations.
	UserRole = UserRoleDao{
		internal.UserRole,
	}
)

// Fill with you ideas below.