// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"context"
	"database/sql"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
	"time"

	"easygoadmin/app/model"
)

// MemberDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type MemberDao struct {
	gmvc.M
	DB      gdb.DB
	Table   string
	Columns MemberColumns
}

// MemberColumns defines and stores column names for table ums_member.
type MemberColumns struct {
	Id            string //                                               
    Openid        string // 用户唯一标识                                  
    Username      string // 用户名                                        
    Password      string // 密码                                          
    MemberLevel   string // 会员等级                                      
    Realname      string // 真实姓名                                      
    Nickname      string // 用户昵称                                      
    Gender        string // 性别（1男 2女 3未知）                         
    Avatar        string // 用户头像                                      
    Birthday      string // 出生日期                                      
    ProvinceCode  string // 户籍省份编号                                  
    CityCode      string // 户籍城市编号                                  
    DistrictCode  string // 户籍区/县编号                                 
    Address       string // 详细地址                                      
    Intro         string // 个人简介                                      
    Signature     string // 个性签名                                      
    Device        string // 设备类型：1苹果 2安卓 3WAP站 4PC站 5后台添加  
    DeviceCode    string // 推送的别名                                    
    PushAlias     string // 推送的别名                                    
    Source        string // 来源：1、APP注册；2、后台添加；               
    Status        string // 是否启用 1、启用  2、停用                     
    AppVersion    string // 客户端版本号                                  
    Code          string // 我的推广码                                    
    LoginIp       string // 最近登录IP                                    
    LoginTime     string // 登录时间                                      
    LoginRegion   string // 上次登录地点                                  
    LoginCount    string // 登录总次数                                    
    CreateUser    string // 添加人                                        
    CreateTime    string // 创建时间                                      
    UpdateUser    string // 修改人                                        
    UpdateTime    string // 更新时间                                      
    Mark          string // 有效标识：1正常 0删除
}

var (
	// Member is globally public accessible object for table ums_member operations.
	Member = MemberDao{
		M:     g.DB("default").Model("ums_member").Safe(),
		DB:    g.DB("default"),
		Table: "ums_member",
		Columns: MemberColumns{
			Id:           "id",             
            Openid:       "openid",         
            Username:     "username",       
            Password:     "password",       
            MemberLevel:  "member_level",   
            Realname:     "realname",       
            Nickname:     "nickname",       
            Gender:       "gender",         
            Avatar:       "avatar",         
            Birthday:     "birthday",       
            ProvinceCode: "province_code",  
            CityCode:     "city_code",      
            DistrictCode: "district_code",  
            Address:      "address",        
            Intro:        "intro",          
            Signature:    "signature",      
            Device:       "device",         
            DeviceCode:   "device_code",    
            PushAlias:    "push_alias",     
            Source:       "source",         
            Status:       "status",         
            AppVersion:   "app_version",    
            Code:         "code",           
            LoginIp:      "login_ip",       
            LoginTime:    "login_time",     
            LoginRegion:  "login_region",   
            LoginCount:   "login_count",    
            CreateUser:   "create_user",    
            CreateTime:   "create_time",    
            UpdateUser:   "update_user",    
            UpdateTime:   "update_time",    
            Mark:         "mark",
		},
	}
)

// Ctx is a chaining function, which creates and returns a new DB that is a shallow copy
// of current DB object and with given context in it.
// Note that this returned DB object can be used only once, so do not assign it to
// a global or package variable for long using.
func (d *MemberDao) Ctx(ctx context.Context) *MemberDao {
	return &MemberDao{M: d.M.Ctx(ctx)}
}

// As sets an alias name for current table.
func (d *MemberDao) As(as string) *MemberDao {
	return &MemberDao{M: d.M.As(as)}
}

// TX sets the transaction for current operation.
func (d *MemberDao) TX(tx *gdb.TX) *MemberDao {
	return &MemberDao{M: d.M.TX(tx)}
}

// Master marks the following operation on master node.
func (d *MemberDao) Master() *MemberDao {
	return &MemberDao{M: d.M.Master()}
}

// Slave marks the following operation on slave node.
// Note that it makes sense only if there's any slave node configured.
func (d *MemberDao) Slave() *MemberDao {
	return &MemberDao{M: d.M.Slave()}
}

// Args sets custom arguments for model operation.
func (d *MemberDao) Args(args ...interface{}) *MemberDao {
	return &MemberDao{M: d.M.Args(args...)}
}

// LeftJoin does "LEFT JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").LeftJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").LeftJoin("user_detail", "ud", "ud.uid=u.uid")
func (d *MemberDao) LeftJoin(table ...string) *MemberDao {
	return &MemberDao{M: d.M.LeftJoin(table...)}
}

// RightJoin does "RIGHT JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").RightJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").RightJoin("user_detail", "ud", "ud.uid=u.uid")
func (d *MemberDao) RightJoin(table ...string) *MemberDao {
	return &MemberDao{M: d.M.RightJoin(table...)}
}

// InnerJoin does "INNER JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").InnerJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").InnerJoin("user_detail", "ud", "ud.uid=u.uid")
func (d *MemberDao) InnerJoin(table ...string) *MemberDao {
	return &MemberDao{M: d.M.InnerJoin(table...)}
}

// Fields sets the operation fields of the model, multiple fields joined using char ','.
// The parameter <fieldNamesOrMapStruct> can be type of string/map/*map/struct/*struct.
func (d *MemberDao) Fields(fieldNamesOrMapStruct ...interface{}) *MemberDao {
	return &MemberDao{M: d.M.Fields(fieldNamesOrMapStruct...)}
}

// FieldsEx sets the excluded operation fields of the model, multiple fields joined using char ','.
// The parameter <fieldNamesOrMapStruct> can be type of string/map/*map/struct/*struct.
func (d *MemberDao) FieldsEx(fieldNamesOrMapStruct ...interface{}) *MemberDao {
	return &MemberDao{M: d.M.FieldsEx(fieldNamesOrMapStruct...)}
}

// Option sets the extra operation option for the model.
func (d *MemberDao) Option(option int) *MemberDao {
	return &MemberDao{M: d.M.Option(option)}
}

// OmitEmpty sets OPTION_OMITEMPTY option for the model, which automatically filers
// the data and where attributes for empty values.
func (d *MemberDao) OmitEmpty() *MemberDao {
	return &MemberDao{M: d.M.OmitEmpty()}
}

// Filter marks filtering the fields which does not exist in the fields of the operated table.
func (d *MemberDao) Filter() *MemberDao {
	return &MemberDao{M: d.M.Filter()}
}

// Where sets the condition statement for the model. The parameter <where> can be type of
// string/map/gmap/slice/struct/*struct, etc. Note that, if it's called more than one times,
// multiple conditions will be joined into where statement using "AND".
// Eg:
// Where("uid=10000")
// Where("uid", 10000)
// Where("money>? AND name like ?", 99999, "vip_%")
// Where("uid", 1).Where("name", "john")
// Where("status IN (?)", g.Slice{1,2,3})
// Where("age IN(?,?)", 18, 50)
// Where(User{ Id : 1, UserName : "john"})
func (d *MemberDao) Where(where interface{}, args ...interface{}) *MemberDao {
	return &MemberDao{M: d.M.Where(where, args...)}
}

// WherePri does the same logic as M.Where except that if the parameter <where>
// is a single condition like int/string/float/slice, it treats the condition as the primary
// key value. That is, if primary key is "id" and given <where> parameter as "123", the
// WherePri function treats the condition as "id=123", but M.Where treats the condition
// as string "123".
func (d *MemberDao) WherePri(where interface{}, args ...interface{}) *MemberDao {
	return &MemberDao{M: d.M.WherePri(where, args...)}
}

// And adds "AND" condition to the where statement.
func (d *MemberDao) And(where interface{}, args ...interface{}) *MemberDao {
	return &MemberDao{M: d.M.And(where, args...)}
}

// Or adds "OR" condition to the where statement.
func (d *MemberDao) Or(where interface{}, args ...interface{}) *MemberDao {
	return &MemberDao{M: d.M.Or(where, args...)}
}

// Group sets the "GROUP BY" statement for the model.
func (d *MemberDao) Group(groupBy string) *MemberDao {
	return &MemberDao{M: d.M.Group(groupBy)}
}

// Order sets the "ORDER BY" statement for the model.
func (d *MemberDao) Order(orderBy ...string) *MemberDao {
	return &MemberDao{M: d.M.Order(orderBy...)}
}

// Limit sets the "LIMIT" statement for the model.
// The parameter <limit> can be either one or two number, if passed two number is passed,
// it then sets "LIMIT limit[0],limit[1]" statement for the model, or else it sets "LIMIT limit[0]"
// statement.
func (d *MemberDao) Limit(limit ...int) *MemberDao {
	return &MemberDao{M: d.M.Limit(limit...)}
}

// Offset sets the "OFFSET" statement for the model.
// It only makes sense for some databases like SQLServer, PostgreSQL, etc.
func (d *MemberDao) Offset(offset int) *MemberDao {
	return &MemberDao{M: d.M.Offset(offset)}
}

// Page sets the paging number for the model.
// The parameter <page> is started from 1 for paging.
// Note that, it differs that the Limit function start from 0 for "LIMIT" statement.
func (d *MemberDao) Page(page, limit int) *MemberDao {
	return &MemberDao{M: d.M.Page(page, limit)}
}

// Batch sets the batch operation number for the model.
func (d *MemberDao) Batch(batch int) *MemberDao {
	return &MemberDao{M: d.M.Batch(batch)}
}

// Cache sets the cache feature for the model. It caches the result of the sql, which means
// if there's another same sql request, it just reads and returns the result from cache, it
// but not committed and executed into the database.
//
// If the parameter <duration> < 0, which means it clear the cache with given <name>.
// If the parameter <duration> = 0, which means it never expires.
// If the parameter <duration> > 0, which means it expires after <duration>.
//
// The optional parameter <name> is used to bind a name to the cache, which means you can later
// control the cache like changing the <duration> or clearing the cache with specified <name>.
//
// Note that, the cache feature is disabled if the model is operating on a transaction.
func (d *MemberDao) Cache(duration time.Duration, name ...string) *MemberDao {
	return &MemberDao{M: d.M.Cache(duration, name...)}
}

// Data sets the operation data for the model.
// The parameter <data> can be type of string/map/gmap/slice/struct/*struct, etc.
// Eg:
// Data("uid=10000")
// Data("uid", 10000)
// Data(g.Map{"uid": 10000, "name":"john"})
// Data(g.Slice{g.Map{"uid": 10000, "name":"john"}, g.Map{"uid": 20000, "name":"smith"})
func (d *MemberDao) Data(data ...interface{}) *MemberDao {
	return &MemberDao{M: d.M.Data(data...)}
}

// All does "SELECT FROM ..." statement for the model.
// It retrieves the records from table and returns the result as []*model.Member.
// It returns nil if there's no record retrieved with the given conditions from table.
//
// The optional parameter <where> is the same as the parameter of M.Where function,
// see M.Where.
func (d *MemberDao) All(where ...interface{}) ([]*model.Member, error) {
	all, err := d.M.All(where...)
	if err != nil {
		return nil, err
	}
	var entities []*model.Member
	if err = all.Structs(&entities); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entities, nil
}

// One retrieves one record from table and returns the result as *model.Member.
// It returns nil if there's no record retrieved with the given conditions from table.
//
// The optional parameter <where> is the same as the parameter of M.Where function,
// see M.Where.
func (d *MemberDao) One(where ...interface{}) (*model.Member, error) {
	one, err := d.M.One(where...)
	if err != nil {
		return nil, err
	}
	var entity *model.Member
	if err = one.Struct(&entity); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entity, nil
}

// FindOne retrieves and returns a single Record by M.WherePri and M.One.
// Also see M.WherePri and M.One.
func (d *MemberDao) FindOne(where ...interface{}) (*model.Member, error) {
	one, err := d.M.FindOne(where...)
	if err != nil {
		return nil, err
	}
	var entity *model.Member
	if err = one.Struct(&entity); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entity, nil
}

// FindAll retrieves and returns Result by by M.WherePri and M.All.
// Also see M.WherePri and M.All.
func (d *MemberDao) FindAll(where ...interface{}) ([]*model.Member, error) {
	all, err := d.M.FindAll(where...)
	if err != nil {
		return nil, err
	}
	var entities []*model.Member
	if err = all.Structs(&entities); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entities, nil
}

// Struct retrieves one record from table and converts it into given struct.
// The parameter <pointer> should be type of *struct/**struct. If type **struct is given,
// it can create the struct internally during converting.
//
// The optional parameter <where> is the same as the parameter of Model.Where function,
// see Model.Where.
//
// Note that it returns sql.ErrNoRows if there's no record retrieved with the given conditions
// from table and <pointer> is not nil.
//
// Eg:
// user := new(User)
// err  := dao.User.Where("id", 1).Struct(user)
//
// user := (*User)(nil)
// err  := dao.User.Where("id", 1).Struct(&user)
func (d *MemberDao) Struct(pointer interface{}, where ...interface{}) error {
	return d.M.Struct(pointer, where...)
}

// Structs retrieves records from table and converts them into given struct slice.
// The parameter <pointer> should be type of *[]struct/*[]*struct. It can create and fill the struct
// slice internally during converting.
//
// The optional parameter <where> is the same as the parameter of Model.Where function,
// see Model.Where.
//
// Note that it returns sql.ErrNoRows if there's no record retrieved with the given conditions
// from table and <pointer> is not empty.
//
// Eg:
// users := ([]User)(nil)
// err   := dao.User.Structs(&users)
//
// users := ([]*User)(nil)
// err   := dao.User.Structs(&users)
func (d *MemberDao) Structs(pointer interface{}, where ...interface{}) error {
	return d.M.Structs(pointer, where...)
}

// Scan automatically calls Struct or Structs function according to the type of parameter <pointer>.
// It calls function Struct if <pointer> is type of *struct/**struct.
// It calls function Structs if <pointer> is type of *[]struct/*[]*struct.
//
// The optional parameter <where> is the same as the parameter of Model.Where function,
// see Model.Where.
//
// Note that it returns sql.ErrNoRows if there's no record retrieved and given pointer is not empty or nil.
//
// Eg:
// user  := new(User)
// err   := dao.User.Where("id", 1).Scan(user)
//
// user  := (*User)(nil)
// err   := dao.User.Where("id", 1).Scan(&user)
//
// users := ([]User)(nil)
// err   := dao.User.Scan(&users)
//
// users := ([]*User)(nil)
// err   := dao.User.Scan(&users)
func (d *MemberDao) Scan(pointer interface{}, where ...interface{}) error {
	return d.M.Scan(pointer, where...)
}

// Chunk iterates the table with given size and callback function.
func (d *MemberDao) Chunk(limit int, callback func(entities []*model.Member, err error) bool) {
	d.M.Chunk(limit, func(result gdb.Result, err error) bool {
		var entities []*model.Member
		err = result.Structs(&entities)
		if err == sql.ErrNoRows {
			return false
		}
		return callback(entities, err)
	})
}

// LockUpdate sets the lock for update for current operation.
func (d *MemberDao) LockUpdate() *MemberDao {
	return &MemberDao{M: d.M.LockUpdate()}
}

// LockShared sets the lock in share mode for current operation.
func (d *MemberDao) LockShared() *MemberDao {
	return &MemberDao{M: d.M.LockShared()}
}

// Unscoped enables/disables the soft deleting feature.
func (d *MemberDao) Unscoped() *MemberDao {
	return &MemberDao{M: d.M.Unscoped()}
}